version: '3.3'
services:
  alibaba-rsocket-broker:
    image: philipz/alibaba-rsocket-broker
    ports:
      - "9997:9997"
      - "9998:9998"
      - "9999:9999"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/config.yml"
    volumes:
      - "./alibaba-broker-server/src/main/config/prometheus.yml:/etc/prometheus/config.yml"

  grafana:
    image: grafana/grafana:6.6.2
    ports:
      - "3000:3000"
